# Generated by Django 6.0.5 on 2026-05-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('varieties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('wet', 'Wet Season'), ('dry', 'Dry Season')], max_length=10)),
                ('year', models.IntegerField()),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=15)),
                ('area_planted_ha', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_cycles', to='varieties.growthstage')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_cycles', to='farms.farm')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='varieties.ricevariety')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('observation', models.TextField()),
                ('issue_type', models.CharField(blank=True, choices=[('pest', 'Pest'), ('disease', 'Disease'), ('weather', 'Weather'), ('nutrient', 'Nutrient Deficiency'), ('other', 'Other')], max_length=15)),
                ('action_taken', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='progress.farmcycle')),
                ('growth_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='varieties.growthstage')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('area_harvested_ha', models.FloatField()),
                ('gross_yield_kg', models.FloatField()),
                ('net_yield_kg', models.FloatField()),
                ('moisture_pct', models.FloatField(default=14.0)),
                ('selling_price_per_kg', models.FloatField(blank=True, null=True)),
                ('gross_income', models.FloatField(blank=True, null=True)),
                ('production_cost', models.FloatField(blank=True, null=True)),
                ('net_income', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('farm_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_record', to='progress.farmcycle')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
    ]
