# Generated by Django 6.0.5 on 2026-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_no', models.IntegerField()),
                ('stage_name', models.CharField(max_length=100)),
                ('days_after_transplanting', models.CharField(max_length=20)),
                ('fertilizer', models.TextField()),
                ('rate_kg_ha', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['app_no'],
            },
        ),
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_no', models.IntegerField(unique=True)),
                ('bbch_min', models.IntegerField()),
                ('bbch_max', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('days_min_paddy', models.IntegerField()),
                ('days_max_paddy', models.IntegerField()),
                ('days_min_upland', models.IntegerField()),
                ('days_max_upland', models.IntegerField()),
                ('what_to_do', models.TextField()),
                ('water_management', models.TextField()),
            ],
            options={
                'ordering': ['stage_no'],
            },
        ),
        migrations.CreateModel(
            name='RiceVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_id', models.CharField(max_length=20, unique=True)),
                ('nsic_code', models.CharField(max_length=30)),
                ('common_name', models.CharField(max_length=100)),
                ('ecosystem', models.CharField(choices=[('irrigated_lowland', 'Irrigated Lowland'), ('rainfed_lowland', 'Rainfed Lowland'), ('upland', 'Upland')], max_length=30)),
                ('season', models.CharField(max_length=30)),
                ('maturity_days', models.IntegerField()),
                ('avg_yield_t_ha', models.FloatField()),
                ('max_yield_t_ha', models.FloatField()),
                ('plant_height_cm', models.IntegerField(blank=True, null=True)),
                ('grain_type', models.CharField(blank=True, max_length=20)),
                ('amylose_pct', models.FloatField(blank=True, null=True)),
                ('submergence_tolerance', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=20)),
                ('drought_tolerance', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=20)),
                ('salinity_tolerance', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=20)),
                ('pest_resistance', models.TextField(blank=True)),
                ('disease_resistance', models.TextField(blank=True)),
                ('optimal_temp_min', models.FloatField(default=22)),
                ('optimal_temp_max', models.FloatField(default=35)),
                ('optimal_rainfall_min', models.IntegerField(default=1200)),
                ('pagasa_climate_types', models.CharField(default='IV', max_length=20)),
                ('year_released', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rice Varieties',
                'ordering': ['variety_id'],
            },
        ),
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pest', 'Pest'), ('disease', 'Disease')], max_length=10)),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('stage_affected', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('control', models.TextField()),
                ('resistant_varieties', models.ManyToManyField(blank=True, related_name='resistant_to', to='varieties.ricevariety')),
            ],
            options={
                'verbose_name_plural': 'Pests & Diseases',
            },
        ),
    ]
