# Generated by Django 6.0.5 on 2026-05-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environmental', '0001_initial'),
        ('farms', '0001_initial'),
        ('varieties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kmeans', 'K-Means'), ('agglomerative', 'Agglomerative Hierarchical'), ('dbscan', 'DBSCAN')], max_length=20)),
                ('training_time_ms', models.FloatField()),
                ('silhouette_score', models.FloatField()),
                ('davies_bouldin', models.FloatField()),
                ('n_clusters', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_cluster', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.clustermodel')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='farms.farm')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environmental.environmentalscan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('rsi_score', models.FloatField()),
                ('suitability_class', models.CharField(max_length=50)),
                ('variety_cluster', models.IntegerField(default=0)),
                ('factor_scores', models.JSONField(default=dict)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recommendations.recommendation')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varieties.ricevariety')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
