# Generated by Django 6.0.5 on 2026-07-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_seed_default_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustermodel',
            name='name',
            field=models.CharField(choices=[('kmeans', 'K-Means')], max_length=20),
        ),
    ]
