# Generated by Django 6.0.5 on 2026-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='days_after_planting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantingguide',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
