# Generated by Django 6.0.5 on 2026-05-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('soil_texture', models.CharField(blank=True, max_length=50)),
                ('organic_matter', models.FloatField(blank=True, null=True)),
                ('drainage', models.CharField(blank=True, max_length=50)),
                ('cec', models.FloatField(blank=True, null=True)),
                ('nitrogen_ppm', models.FloatField(blank=True, null=True)),
                ('bulk_density', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('temp_at_flowering', models.FloatField(blank=True, null=True)),
                ('annual_rainfall_mm', models.FloatField(blank=True, null=True)),
                ('seasonal_rainfall_mm', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('solar_radiation', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('sunshine_hours', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('slope_pct', models.FloatField(blank=True, null=True)),
                ('flood_risk', models.CharField(blank=True, max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='farms.farm')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
